USE eqa_prod
go
CREATE TABLE dbo.ACADEMIC_YEAR_TYPE
(
    academic_year_type      varchar(4) NOT NULL,
    academic_year_type_desc descr      NOT NULL,
    CONSTRAINT PK_ACADEMIC_YEAR_TYPE
    PRIMARY KEY CLUSTERED (academic_year_type)
)
LOCK DATAROWS
go
IF OBJECT_ID('dbo.ACADEMIC_YEAR_TYPE') IS NOT NULL
    PRINT '<<< CREATED TABLE dbo.ACADEMIC_YEAR_TYPE >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE dbo.ACADEMIC_YEAR_TYPE >>>'
go
GRANT REFERENCES ON dbo.ACADEMIC_YEAR_TYPE TO eqa_user
go
GRANT SELECT ON dbo.ACADEMIC_YEAR_TYPE TO eqa_user
go
GRANT SELECT ON dbo.ACADEMIC_YEAR_TYPE TO read_only
go
GRANT SELECT ON dbo.ACADEMIC_YEAR_TYPE TO rma_users
go
GRANT INSERT ON dbo.ACADEMIC_YEAR_TYPE TO eqa_user
go
GRANT DELETE ON dbo.ACADEMIC_YEAR_TYPE TO eqa_user
go
GRANT UPDATE ON dbo.ACADEMIC_YEAR_TYPE TO eqa_user
go
GRANT DELETE STATISTICS ON dbo.ACADEMIC_YEAR_TYPE TO eqa_user
go
GRANT TRUNCATE TABLE ON dbo.ACADEMIC_YEAR_TYPE TO eqa_user
go
GRANT UPDATE STATISTICS ON dbo.ACADEMIC_YEAR_TYPE TO eqa_user
go
GRANT TRANSFER TABLE ON dbo.ACADEMIC_YEAR_TYPE TO eqa_user
go
