USE eqa_prod
go
ALTER TABLE dbo.ACRD_INHERITANCE_MAP
    ADD CONSTRAINT AK_INHERITED_FROM_PROVIDER
    UNIQUE NONCLUSTERED (inherited_from_moe_provider_id,inherited_from_location)
go
ALTER TABLE dbo.ACRD_INHERITANCE_MAP
    ADD CONSTRAINT AK_INHERITING_PROVIDER
    UNIQUE NONCLUSTERED (inheriting_moe_provider_id,inheriting_location)
go
ALTER TABLE dbo.AMAP
    ADD CONSTRAINT AK_AK_AMAP_AMAP
    UNIQUE NONCLUSTERED (amap_number)
go
ALTER TABLE dbo.AMAP_COVERAGE
    ADD CONSTRAINT AK_AMAP_COV
    UNIQUE NONCLUSTERED (amap_id,std_version_id)
go
ALTER TABLE dbo.ASSESSMENT_SESSION
    ADD CONSTRAINT cnstr_ses_code
    UNIQUE NONCLUSTERED (session_code,assessment_cycle_id)
go
ALTER TABLE dbo.ASSESSMENT_SESSION
    ADD CONSTRAINT cnstr_title
    UNIQUE NONCLUSTERED (title,assessment_cycle_id)
go
ALTER TABLE dbo.ASSESSMENT_SESSION_COMPONENT
    ADD CONSTRAINT uidx_assessment_session_com_01
    UNIQUE NONCLUSTERED (std_number,academic_year,assessment_session_id)
go
ALTER TABLE dbo.ASSESS_SESSION_RELATIONSHIP
    ADD CONSTRAINT AK_ASSESS_SESSION_RELATIONSHIP
    UNIQUE NONCLUSTERED (assessment_session_id,related_assessment_session_id,assessment_session_rel_type)
go
ALTER TABLE dbo.BATCH_FILE_TYPE_CODE
    ADD CONSTRAINT FILE_TYPE_UQ_BATCH_TYPE
    UNIQUE NONCLUSTERED (file_type_code,batch_type_code)
go
ALTER TABLE dbo.CFN_CATEGORY_STATUS
    ADD CONSTRAINT AK_CFN_CATEGORY_STATUS
    UNIQUE NONCLUSTERED (cfn_catg_status_code,cfn_system_code)
go
ALTER TABLE dbo.CFN_DEPTH_TYPE
    ADD CONSTRAINT AK_AK_CFN_DEPTH_TYPE_CFN_DEPT
    UNIQUE NONCLUSTERED (cfn_depth_code,cfn_system_code)
go
ALTER TABLE dbo.COUNTRY_CODE
    ADD CONSTRAINT uidx_country_code_01
    UNIQUE NONCLUSTERED (country_short_code)
go
ALTER TABLE dbo.COURSE_VERSION
    ADD CONSTRAINT AK_COURSE_VERSION
    UNIQUE NONCLUSTERED (course_id,course_version_number)
go
ALTER TABLE dbo.ENDORSEMENT
    ADD CONSTRAINT AK_ENDORSEMENT
    UNIQUE NONCLUSTERED (endorsement_code)
go
ALTER TABLE dbo.ENDORSEMENT_VERSION
    ADD CONSTRAINT AK_ENDORSEMENT_VERSION
    UNIQUE NONCLUSTERED (endorsement_id,endorsement_version_number)
go
ALTER TABLE dbo.ENTRY
    ADD CONSTRAINT IDX_ENTRY_06
    UNIQUE NONCLUSTERED (entry_id,academic_year)
go
ALTER TABLE dbo.EQA_SETTING
    ADD CONSTRAINT AK_EQA_SETTING_02
    UNIQUE NONCLUSTERED (name)
go
ALTER TABLE dbo.EXAM_CENTRE_ALLOC_RULE
    ADD CONSTRAINT AK_EXAM_CENTRE_ALLOC_RULE
    UNIQUE NONCLUSTERED (moe_provider_id,location,eca_gender_code)
go
ALTER TABLE dbo.MERGE_REQUEST
    ADD CONSTRAINT AK_MERGE_REQUEST
    UNIQUE NONCLUSTERED (merge_request_number)
go
ALTER TABLE dbo.PANEL_AD_REGION
    ADD CONSTRAINT AK_AK_PANEL_ADVERTISE_PANEL_AD
    UNIQUE NONCLUSTERED (panel_id,region_code)
go
ALTER TABLE dbo.PROVIDER_IA_RESULT
    ADD CONSTRAINT IDX_PROVIDER_IA_RESULTS_01
    UNIQUE NONCLUSTERED (provider_id,location,academic_year)
go
ALTER TABLE dbo.QFN_EXEMPTION_TABLE
    ADD CONSTRAINT IDX_QFN_EXEMPTION_TABLE_01
    UNIQUE NONCLUSTERED (rules_group_id,qfn_exmptn_tbl_title)
go
ALTER TABLE dbo.QFN_SCENARIO_QFN_COMPONENT
    ADD CONSTRAINT QFN_SCENARIO_QFN_UNIQ_SEQ
    UNIQUE NONCLUSTERED (qfn_scenario_id,seq_number)
go
ALTER TABLE dbo.QFN_SCENARIO_STD_COMPONENT
    ADD CONSTRAINT QFN_SCENARIO_STD_UNIQ_SEQ
    UNIQUE NONCLUSTERED (qfn_scenario_id,seq_number)
go
ALTER TABLE dbo.QFN_VER_ENDORSEMENT_VER
    ADD CONSTRAINT AK_QFN_VER_ENDORSEMENT_VER
    UNIQUE NONCLUSTERED (qfn_version_id,endorsement_version_id)
go
ALTER TABLE dbo.RECONSIDERATION_ENTRY
    ADD CONSTRAINT AK_RECONS_ENTRY_ENTRY
    UNIQUE NONCLUSTERED (entry_id)
go
ALTER TABLE dbo.REPORT_CONTEXT
    ADD CONSTRAINT AK_REPORT_CONTEXT_BUSINESS_KEY
    UNIQUE NONCLUSTERED (report_id,report_category_code)
go
ALTER TABLE dbo.REPORT_PARAMETER_CONFIG
    ADD CONSTRAINT AK_RPC_BUSINESS_KEY
    UNIQUE NONCLUSTERED (report_parameter_id,report_category_code)
go
ALTER TABLE dbo.SMS_DIST_LIST_CODE
    ADD CONSTRAINT AK_SMS_DIST_LIST_CODE
    UNIQUE NONCLUSTERED (groupwise_name)
go
ALTER TABLE dbo.STD_CONTEXT_MAP
    ADD CONSTRAINT IDX_UQ_STD_CONTEXT
    UNIQUE NONCLUSTERED (std_context_map_id,std_number)
go
ALTER TABLE dbo.STD_CONTEXT_MAP
    ADD CONSTRAINT IDX_UQ_STD_CONTEXT_CODE
    UNIQUE NONCLUSTERED (std_number,context_code)
go
